[package]
name = "ghost-toolkit"
version = "0.0.1"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", default-features = false, features = [
    "rustls-tls",
    "http2",
] }
yansi = "1.0.1"

[profile.release]
strip = true
lto = "fat"
codegen-units = 1